### ISSUE TITLE
Could not initialize class de.digitalcollections.solrocr.lucene.OcrHighlighter

### ISSUE THREAD

**Issue by Sozialarchiv** [dbmdz/solr-ocrhighlighting#127]
I followed the installation instruction. But if I enter the search url (http://localhost:8984/solr/test/select?q=ocr_text:%22Test%22~10&hl=true&hl.ocr.fl=ocr_text) I get the following error

java.lang.NoClassDefFoundError: Could not initialize class de.digitalcollections.solrocr.lucene.OcrHighlighter

Thank you very much for your help.

**Comment by Sozialarchiv** [comment]
Solr version was to small.

Can you please change here https://dbmdz.github.io/solr-ocrhighlighting/installation/ change Solr >= 7.x to => 7.5

**Comment by jbaiter** [comment]
Oh my, sorry about that! The version specifier was adjusted in the README, but I forgot about the docs :scream_cat:! Will be fixed asap!

**Comment by Sozialarchiv** [comment]
Thank you
