### ISSUE TITLE
mirador broken on frontend example

### ISSUE THREAD

**Issue by atomotic** [dbmdz/solr-ocrhighlighting#148]
mirador is currently broken on [frontend example](https://github.com/dbmdz/solr-ocrhighlighting/blob/main/example/frontend/viewer.html) ([tested here](https://ocrhl.jbaiter.de/viewer/?manifest=https://ocrhl.jbaiter.de/iiif/presentation/bnl:1540858_1862-02-22/manifest&cv=P2&q=bologna))  
the search query could be populated easily with [defaultSearchQuery](https://github.com/ProjectMirador/mirador/wiki/M3---Mirador-3-Frequently-Asked-Questions#q-is-it-possible-to-show-search-results-directly-without-the-user-typing-in-the-search-term), without dispatching actions to the store

**Comment by jbaiter** [comment]
Ah, thanks for reporting, that code predates the `defaultSearchQuery` parameter, I'll try to update the code when I find the time :-)
