### ISSUE TITLE
Link https://dbmdz.github.io/solr-ocrhighlighting/alternatives/ doesn't work

### ISSUE THREAD

**Issue by jsbien** [dbmdz/solr-ocrhighlighting#298]

**Comment by jbaiter** [comment]
Sorry about that, I swiched the documentation setup to provide multiple versions at once and forgot to adjust the links in the README, the correct link for the current version is https://dbmdz.github.io/solr-ocrhighlighting/latest/alternatives/.

I just updated the README accordingly, thank you for submitting the issue!!
