### ISSUE TITLE
Link in README.md at Features on MiniOCR does not work

### ISSUE THREAD

**Issue by BFallert** [dbmdz/solr-ocrhighlighting#309]
In the section "Features / Index hOCR, ALTO or MiniOCR directly ..." the link that is registered at **`MiniOCR`** does not work anymore.

Current: https://dbmdz.github.io/solr-ocrhighlighting/latet/formats/

Possible options: 
- https://dbmdz.github.io/solr-ocrhighlighting/0.8.3/
- https://dbmdz.github.io/solr-ocrhighlighting/wip/

Both **latet** and **formats** were probably removed.

**Comment by jbaiter** [comment]
Ooops, thank you! Will be fixed :-)

**Comment by jbaiter** [comment]
Fixed in https://github.com/dbmdz/solr-ocrhighlighting/commit/90147b26e4a4a12315a51b48f6fde3c8962768fa
