### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by DavidHaskiya** [dbmdz/solr-ocrhighlighting#354]
Hi, 
I noticed the demo is down. Any chance it could be re-awekened?

Cheers!

/D

**Comment by jbaiter** [comment]
Ooops, sorry about that, seems the VPS it's been running on has rebooted and it failed to come up again, I'll debug in the evening and try to get it up again.

**Comment by marsaoua** [comment]
The Demo is still down....

**Comment by jbaiter** [comment]
It's up again!
