### ISSUE TITLE
HTTP Error 404 while running  ingest.py 

### ISSUE THREAD

**Issue by marsaoua** [dbmdz/solr-ocrhighlighting#372]
The links used for the data for the examaple are not found. Both links throw HTTP Error 404

**Comment by jbaiter** [comment]
Sorry about that, will try to fix asap.

**Comment by jbaiter** [comment]
Should be fixed now, can you try again?

**Comment by marsaoua** [comment]
Yes, it worked! Thank you for the quick fix :) :+1:
