### ISSUE TITLE
SolrException `undefined field null`

### ISSUE THREAD

**Issue by atomotic** [dbmdz/solr-ocrhighlighting#396]
I am currently experiencing an issue with the latest plugin (tried with Solr 9.0 and 9.4). While each query successfully returns the correct values in both `docs` and `ocrHighlighting`, the response status consistently remains at 400, accompanied by the following error:

```
"error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"undefined field null",
    "code":400}}
```

I see the same error in solr.log

```
solr-1  | 2024-02-20 19:37:06.553 ERROR (qtp503938393-25) [ x:ocr] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: undefined field null => org.apache.solr.common.SolrException: undefined field null
solr-1  |       at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1468)
solr-1  | org.apache.solr.common.SolrException: undefined field null
```
I have also tested the plugin with the provided example compose configuration, using [this schema](https://github.com/dbmdz/solr-ocrhighlighting/blob/main/example/solr/core/schema.xml), and encountered the same behavior.

Thanks for your help

**Comment by jbaiter** [comment]
Thanks for reporting, will investigate tomorrow and update the integration tests, this should not have slipped through 😬

**Comment by atomotic** [comment]
Perhaps I am making a mistake on my end, but I have encountered the same behavior with Solr 9 and plugin version 0.8.3. Could this be related to something in the hOCR files (I have used the latest Tesseract 5.3.4)?"

**Comment by jbaiter** [comment]
Hey Raffaele, sorry for not updating this issue. I tried reproducing the issue with Solr 9.5 and the local example setup, but could not trigger the issue, all of the queries I tried run successfully with response code 200 and there is no `errors` key in the response 🤔 

Since you're using the schema from the example, I'd rule that out. I'd also be very surprised if the problem is caused by the OCR files you're using, the stack frame from your log excerpt indicates that the error occurs in some piece of code that queries the schema.

Are you able to share a trimmed-down docker-compose setup with some sample data that reliably reproduces the issue?

And if you're handy with a debugger, could you add a conditional breakpoint on `IndexSchema#getDynamicFieldType` that triggers when the passed `fieldName` argument is `null`? That should tell us where this issue is initially triggered.

**Comment by atomotic** [comment]
I have temporarily opened the solr with the issue:
https://arbor.search.mlol.link/solr/ocr/select?q=ocr_text:%22Bologna%22~10&hl.ocr.fl=ocr_text&hl=true

The only thing I've modififed in the docker-compose

enabled the facet handler
```
<requestHandler name="/select" class="solr.SearchHandler">
    <arr name="components">
      <str>query</str>
      <str>ocrHighlight</str>
      <str>highlight</str>
      <str>facet</str>
    </arr>
  </requestHandler>
```

and added something to the schema:

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Solr managed schema - automatically generated - DO NOT EDIT -->
<schema name="coordinateHighlight" version="1.0">
  <uniqueKey>id</uniqueKey>
  <fieldType name="date" class="solr.DatePointField" docValues="true" />
  <fieldType name="int" class="solr.IntPointField" docValues="true" />
  <fieldType name="string" class="solr.StrField" omitNorms="true" sortMissingLast="true" />
  <fieldType name="text" class="solr.TextField">
    <analyzer>
      <tokenizer class="solr.StandardTokenizerFactory" />
      <filter class="solr.LowerCaseFilterFactory" />
      <filter class="solr.StopFilterFactory" />
      <filter class="solr.PorterStemFilterFactory" />
    </analyzer>
  </fieldType>
  <fieldType name="text_ocr" class="solr.TextField" termVectors="true"
    storeOffsetsWithPositions="true">
    <analyzer type="index">
      <charFilter class="solrocr.ExternalUtf8ContentFilterFactory" />
      <charFilter class="solrocr.OcrCharFilterFactory" />
      <tokenizer class="solr.StandardTokenizerFactory" />
      <filter class="solr.LowerCaseFilterFactory" />
      <filter class="solr.StopFilterFactory" />
      <filter class="solr.PorterStemFilterFactory" />
    </analyzer>
    <analyzer type="query">
      <tokenizer class="solr.StandardTokenizerFactory" />
      <filter class="solr.LowerCaseFilterFactory" />
      <filter class="solr.StopFilterFactory" />
      <filter class="solr.PorterStemFilterFactory" />
    </analyzer>
  </fieldType>
  <field name="author" type="text" multiValued="true" indexed="true" stored="true" />
  <field name="date" type="date" multiValued="false" indexed="true" stored="true" />
  <field name="id" type="string" multiValued="false" indexed="true" required="true" stored="true" />
  <field name="parent" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="parent_title" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="issue_id" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="language" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="newspaper_part" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="newspaper_title" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="ocr_text" type="text_ocr" multiValued="false" indexed="true" stored="true" />
  <field name="publisher" type="text" multiValued="false" indexed="true" stored="true" />
  <field name="source" type="string" multiValued="false" indexed="true" required="true"
    stored="true" />
  <field name="subtitle" type="text" multiValued="true" indexed="true" stored="true" />
  <field name="title" type="text" multiValued="true" indexed="true" stored="true" />
  <field name="iiif" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="cover" type="string" multiValued="false" indexed="false" stored="true" />
  <field name="year" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="collection" type="string" multiValued="false" indexed="true" stored="true" />
  <field name="type" type="string" multiValued="false" indexed="true" stored="true" />


</schema>
```


I have to learn, but I can try with the debugger as you suggest. Thanks!

**Comment by jbaiter** [comment]
So I just tried the example setup with your modified schema and solrconfig and I'm still not able to reproduce this. This indicates that it's indeed somehow triggered by your data 🤔

**Comment by atomotic** [comment]
ok thanks. let me try also using ocr extracted with an older tesseract release

**Comment by atomotic** [comment]
I have tried with a hocr (extracted with tesseract 5.1.0) that works correctly in production with the plugin version 0.6.0, attached below.  
Tested with the example compose (without any tweaks), same 400 error

[example.zip](https://github.com/dbmdz/solr-ocrhighlighting/files/14484258/example.zip)

**Comment by jbaiter** [comment]
Thank you, now I can reproduce it 👍🏾 I was missing the `hl=true` parameter when testing.

The issue is that you're enabling regular highlighting via `hl=true`, but you're not defining which fields should be highlighted. This leads the default Solr highlighter to look for highlight fields by itself, and that's where the exeption occurs.

I'll try to dig deeper into this tomorrow to see why this is happening, but for now you can simply add an additional request parameter `hl.fl=` (i.e. the empty string) and the error should disappear.

**Comment by atomotic** [comment]
thanks for the support!
